### ISSUE TITLE
Git conflict markers is too dark

### ISSUE THREAD

**Issue by thanhbinh01234** [catppuccin/vscode#42]
The color of code inside git conflict marker block is too dark when I'm using Latte variant:

<img width="932" alt="Screen Shot 2022-09-21 at 20 02 02" src="https://user-images.githubusercontent.com/42236390/191510790-496dbae0-40b4-4844-86a4-c7e0ac2fdfb1.png">

**Comment by nekowinston** [comment]
noted, thanks for reporting it

**Comment by backwardspy** [comment]
i am interested in working on this.

i had a go at choosing colours for all four flavours as they seem to be using the same colours at the moment, so now they're consistent with each flavour (albeit darkened/lightened accordingly.)

**latte**
<img width="892" alt="latte" src="https://user-images.githubusercontent.com/289746/196733330-8bc0e356-5021-4d01-b2ed-6c4fade82494.png">

**frappe**
<img width="892" alt="frappe" src="https://user-images.githubusercontent.com/289746/196733364-7bf184a2-3653-493a-9446-36db0353b0b5.png">

**macchiato**
<img width="892" alt="macchiato" src="https://user-images.githubusercontent.com/289746/196733419-e5e3ea29-1f46-4e9e-a702-51e8d77c063c.png">

**mocha**
<img width="892" alt="mocha" src="https://user-images.githubusercontent.com/289746/196733444-cc18f2a2-125c-4488-a18f-0f4a32ac9955.png">

please let me know what you think! if i'm going down the right track and nobody is already working on this, then i'll be happy to open a PR.

**Comment by sgoudham** [comment]
Thank you for showcasing your work! 

@nekowinston and I actually started to improve the highlights in the [dev](https://github.com/catppuccin/vscode) branch and improved the diff highlights there. I believe we released a preview version 2.1.1 on the VSCode marketplace. 

Could you please switch to the pre-release version and check if the highlights are looking better on all the flavours? @thanhbinh01234 

(Apologies if this is already the pre-release version, I don't use VSCode day to day 😅)

**Comment by backwardspy** [comment]
can confirm v2.1.1 does not resolve this particular issue

![image](https://user-images.githubusercontent.com/289746/197052243-7af243f7-e913-4df5-911c-557d1315aaee.png)

**Comment by sgoudham** [comment]
Ah okay, interesting. I think the highlights we might have fixed were to do with the popup instead of the merge conflict editor. 

In that case, I think it would make perfect sense to open up a PR with your current changes against the dev branch! Thanks for the work you've put into it already. @backwardspy

**Comment by backwardspy** [comment]
i shall do that :)

**Comment by nekowinston** [comment]
@backwardspy I'd appreciate if you could share the highlights you used, or even better, open a PR for it. 🙂

This repo is finally in a state where this should be less troublesome.

**Comment by backwardspy** [comment]
sounds good, i'm hoping to have some time for this tomorrow.
